const OBJECT_NAME_CAPITALIZED_PLACEHOLDER = '<%objectNameCapitalized%>';
const OBJECT_NAME_PLACEHOLDER = '<%objectName%>';
const PACKAGE_NAME_PLACEHOLDER = '<%packageName%>';
const OBJECT_NAME_LOWERED_PLACEHOLDER = '<%objectNameLowered%>';

const CURR_DIR = process.cwd();

const SPRING_BOOT_COMPONENT_BOILERPLATE_DIR = './src/templates/springBootComponentTemplate.txt';
const SPRING_BOOT_REPOSITORY_BOILERPLATE_DIR = './src/templates/springBootRepositoryTemplate.txt';
const SPRING_BOOT_SERVICE_BOILERPLATE_DIR = './src/templates/springBootServiceTemplate.txt';
const SPRING_BOOT_SERVICE_IMPL_BOILERPLATE_DIR = './src/templates/springBootServiceImplTemplate.txt';

const SPRING_BOOT_CONTROLLERS_SAVE_DIRECTORY = `${CURR_DIR}/controllers`;
const SPRING_BOOT_SERVICES_SAVE_DIRECTORY = `${CURR_DIR}/services`;
const SPRING_BOOT_SERVICES_IMPL_SAVE_DIRECTORY = `${CURR_DIR}/services/impl`;
const SPRING_BOOT_REPOSITORIES_SAVE_DIRECTORY = `${CURR_DIR}/repositories`;
const SPRING_BOOT_ENTITIES_SAVE_DIRECTORY = `${CURR_DIR}/entities`;
const UTF8_ENCODING = 'utf8';

const SPRING_BOOT_SAVE_DIRECTORIES = {
  CONTROLLERS: `${CURR_DIR}/controllers`,
  SERVICES: `${CURR_DIR}/services`,
  SERVICESIMPL: `${CURR_DIR}/services/impl`,
  ENTITIES: `${CURR_DIR}/entities`,
  REPOSITORIES: `${CURR_DIR}/repositories`
};

module.exports = {
  OBJECT_NAME_CAPITALIZED_PLACEHOLDER,
  OBJECT_NAME_PLACEHOLDER,
  PACKAGE_NAME_PLACEHOLDER,
  OBJECT_NAME_LOWERED_PLACEHOLDER,
  SPRING_BOOT_COMPONENT_BOILERPLATE_DIR,
  SPRING_BOOT_REPOSITORY_BOILERPLATE_DIR,
  SPRING_BOOT_SERVICE_BOILERPLATE_DIR,
  SPRING_BOOT_SERVICE_IMPL_BOILERPLATE_DIR,
  SPRING_BOOT_SAVE_DIRECTORIES,
  SPRING_BOOT_CONTROLLERS_SAVE_DIRECTORY,
  SPRING_BOOT_SERVICES_SAVE_DIRECTORY,
  SPRING_BOOT_SERVICES_IMPL_SAVE_DIRECTORY,
  SPRING_BOOT_REPOSITORIES_SAVE_DIRECTORY,
  SPRING_BOOT_ENTITIES_SAVE_DIRECTORY,
  CURR_DIR,
  UTF8_ENCODING
};